// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:61b06ded-990b-4403-bfd2-8c0c3c7f1254",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "71abfcfa906f4306959306e87cd1ac5e",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
